# Generated by Django 5.0.6 on 2024-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("to_do_assigned", "To Do Assigned"),
                    ("event_created", "Event Created"),
                ],
                max_length=30,
            ),
        ),
    ]
