# Generated by Django 5.0.6 on 2024-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="remarks",
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_in_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_out_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
