# Generated by Django 5.0.6 on 2024-07-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0002_remove_attendance_remarks_attendance_clock_in_note_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
    ]
