# Generated by Django 5.0.6 on 2024-07-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"get_latest_by": "date", "ordering": ["date"]},
        ),
    ]
