# Generated by Django 5.0.6 on 2024-07-10 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatroomparticipant",
            unique_together={("employee", "chat_room")},
        ),
    ]
