# Generated by Django 5.0.6 on 2024-07-11 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_alter_chatroomparticipant_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
