# Generated by Django 5.0.6 on 2024-07-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_chatroom_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatroomparticipant",
            unique_together=set(),
        ),
    ]
