# Generated by Django 5.0.6 on 2024-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="username",
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
