# Generated by Django 5.0.6 on 2024-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_departmentuser_department_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
