# Generated by Django 5.0.6 on 2024-07-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_department_head_delete_departmentuser"),
        ("users", "0004_alter_employee_managers_alter_employee_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="departments.department",
            ),
        ),
    ]
