# Generated by Django 5.0.6 on 2024-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(max_length=50),
        ),
    ]
