# Generated by Django 5.0.6 on 2024-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_employee_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="certifications",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="employee",
            name="hobbies",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="mbti",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="projects",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.JSONField(default=list),
        ),
    ]
