# Generated by Django 5.0.6 on 2024-07-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_employee_certifications_employee_hobbies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="projects",
        ),
        migrations.AlterField(
            model_name="employee",
            name="certifications",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hobbies",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
