# Generated by Django 5.0.6 on 2024-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_employee_projects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="certifications",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hobbies",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
