# Generated by Django 5.0.6 on 2024-07-09 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="effective_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
