# Generated by Django 5.0.6 on 2024-07-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tag",
            field=models.CharField(
                choices=[
                    ("company_event", "Company Event"),
                    ("family_event", "Family Event"),
                    ("certificate", "Certificate"),
                    ("external_event", "External Event"),
                    ("public_holiday", "Public Holiday"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=20,
            ),
        ),
    ]
