# Generated by Django 5.0.6 on 2024-07-14 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_leavepolicy_companypolicy_delete_annualleave"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavepolicy",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="leavepolicy",
            name="default_leave_days",
        ),
        migrations.RemoveField(
            model_name="leavepolicy",
            name="description",
        ),
        migrations.RemoveField(
            model_name="leavepolicy",
            name="name",
        ),
        migrations.RemoveField(
            model_name="leavepolicy",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="annual_leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="employee",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="used_leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="CompanyPolicy",
        ),
    ]
